// ÉDITEZ CE FICHIER : ajoutez vos cours et évaluations.
// Placez les PDF dans le dossier pdfs/<theme>/ et indiquez leur chemin.
// "total" = nombre de points de l'évaluation.
const THEMES = [
  { id: "cybersecurite", nom: "Cybersécurité", desc: "De zéro à expert : systèmes, réseaux, pentest, SOC, forensic",
    page: "cyber.html", pct: "pCyb", meta: "20 niveaux · 64 modules · évaluations",
    lecons: [], evaluations: [] },
  { id: "anglais", nom: "Anglais", desc: "Formation intensive en 30 cours, avec déblocage progressif",
    page: "anglais.html", pct: "pAng", meta: "6 modules · 30 cours · évaluations",
    lecons: [], evaluations: [] },
  { id: "chinois", nom: "Chinois", desc: "Mandarin : pinyin, tons, vocabulaire du quotidien",
    page: "chinois.html", pct: "pm-chinois", meta: "Parcours A0 → C2 · évaluations",
    lecons: [], evaluations: [] },
  { id: "espagnol", nom: "Espagnol", desc: "Parlez et comprenez l'espagnol pas à pas",
    page: "module.html?t=espagnol", pct: "pm-espagnol", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
  { id: "francais", nom: "Français", desc: "Grammaire, conjugaison et expression",
    page: "module.html?t=francais", pct: "pm-francais", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
  { id: "orthographe", nom: "Orthographe", desc: "Fini les fautes : homophones, accords, pièges",
    page: "module.html?t=orthographe", pct: "pm-orthographe", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
  { id: "coderoute", nom: "Code de la route", desc: "Préparez l'examen : priorités, panneaux, sécurité",
    page: "module.html?t=coderoute", pct: "pm-coderoute", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
  { id: "culture", nom: "Culture générale", desc: "Géographie, arts, sciences : l'essentiel à connaître",
    page: "module.html?t=culture", pct: "pm-culture", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
  { id: "histoire", nom: "Histoire-Géographie", desc: "Les grandes périodes et les repères clés",
    page: "module.html?t=histoire", pct: "pm-histoire", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
  { id: "maths", nom: "Mathématiques", desc: "Fractions, calcul, logique : bases solides",
    page: "module.html?t=maths", pct: "pm-maths", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
  { id: "eloquence", nom: "Éloquence", desc: "Convaincre et captiver à l'oral",
    lecons: [{ id: "l1", titre: "Leçon 1", pdf: "pdfs/eloquence/lecon-1.pdf" }],
    evaluations: [{ id: "e1", titre: "Évaluation 1", pdf: "pdfs/eloquence/eval-1.pdf", total: 20 }] },
  { id: "politique", nom: "Politique", desc: "Institutions, idées et débats",
    lecons: [{ id: "l1", titre: "Leçon 1", pdf: "pdfs/politique/lecon-1.pdf" }],
    evaluations: [{ id: "e1", titre: "Évaluation 1", pdf: "pdfs/politique/eval-1.pdf", total: 20 }] },
  { id: "sciences", nom: "Sciences", desc: "Comprendre le monde",
    lecons: [{ id: "l1", titre: "Leçon 1", pdf: "pdfs/sciences/lecon-1.pdf" }],
    evaluations: [{ id: "e1", titre: "Évaluation 1", pdf: "pdfs/sciences/eval-1.pdf", total: 20 }] },
  { id: "italien", nom: "Italien", desc: "Parlez Italien dès maintenant ",
    page: "module.html?t=italien", pct: "pm-italien", meta: "Parcours progressif · évaluations",
    lecons: [], evaluations: [] },
];